### ISSUE TITLE
Add toggle to switch by date/by days since threshold

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [holgerdell/COVID-19-plots#5]
The threshold could be days since first death or days since first 100 detected cases.
This would allow to compare trajectories of different countries by aligning the curves on a sensible starting point.

**Comment by holgerdell** [comment]
Yes, feel free to add a toggle for that. Also interesting would be "estimated doubling time" when you hover over a data point.

**Comment by make-github-pseudonymous-again** [comment]
Fixed by #12.
